### ISSUE TITLE
Critical: why C and Python bindings

### ISSUE THREAD

**Issue by Madoshakalaka** [eddieantonio/lcg-rs#1]
write everything in rust bro

**Comment by eddieantonio** [comment]
alas, some people avoid [carcinization](https://en.wikipedia.org/wiki/Carcinisation)

![Predictably, the spy from TF2 evolves into a crab](https://user-images.githubusercontent.com/2294397/142203717-7f0c0bc0-2739-456f-935f-273cd3230995.png)

**Comment by Madoshakalaka** [comment]
good meme, now mine
